# =============================================
# CONFIGURATION POSTGRESQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5433/recouvrement_batch
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de connexions
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# =============================================
# CONFIGURATION JPA / HIBERNATE
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# CONFIGURATION SPRING BATCH
# =============================================
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# =============================================
# LOGGING
# =============================================
logging.level.org.springframework.batch=INFO
logging.level.org.hibernate.SQL=DEBUG